"""fourth migration upgrade role in user table

Revision ID: e9d5823624bc
Revises: 90afab5480bc
Create Date: 2025-07-15 15:54:07.074918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d5823624bc'
down_revision: Union[str, Sequence[str], None] = '90afab5480bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('users', 'confirm_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
